/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FarmerProfile {
  'bio' : [] | [string],
  'farmSize' : string,
  'farmType' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'phone' : string,
  'location' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'buyer' : null } |
  { 'farmer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createProfile' : ActorMethod<
    [string, string, string, string, string, [] | [string], UserRole],
    undefined
  >,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllUsers' : ActorMethod<[], Array<FarmerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'getProfile' : ActorMethod<[Principal], [] | [FarmerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [FarmerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[FarmerProfile], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];