/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'buyer' : IDL.Null,
  'farmer' : IDL.Null,
});
export const Time = IDL.Int;
export const FarmerProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'farmSize' : IDL.Text,
  'farmType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        UserRole,
      ],
      [],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(FarmerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FarmerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([FarmerProfile], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'buyer' : IDL.Null,
    'farmer' : IDL.Null,
  });
  const Time = IDL.Int;
  const FarmerProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'farmSize' : IDL.Text,
    'farmType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          UserRole,
        ],
        [],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(FarmerProfile)], ['query']),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FarmerProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FarmerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([FarmerProfile], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };